// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BandItems: typeof import('./src/components/Band/BandItems.vue')['default']
    BandList: typeof import('./src/components/Band/BandList.vue')['default']
    BaseButton: typeof import('./src/components/UI/BaseButton.vue')['default']
    IconMoon: typeof import('./src/components/Icons/IconMoon.vue')['default']
    IconSun: typeof import('./src/components/Icons/IconSun.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
  }
}

export {}
