// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BandDetailedView: typeof import('./src/components/Band/BandDetailedView.vue')['default']
    BandItems: typeof import('./src/components/Band/BandItems.vue')['default']
    BandList: typeof import('./src/components/Band/BandList.vue')['default']
    DetailedView: typeof import('./src/components/Band/DetailedView.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  }
}

export {}
