// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BandList: typeof import('./src/components/Band/BandList.vue')['default']
    BandTracks: typeof import('./src/components/Band/BandTracks.vue')['default']
    BaseButton: typeof import('./src/components/UI/BaseButton.vue')['default']
    BaseCard: typeof import('./src/components/UI/BaseCard.vue')['default']
    BaseFileProgress: typeof import('./src/components/UI/BaseFileProgress.vue')['default']
    BaseInput: typeof import('./src/components/UI/BaseInput.vue')['default']
    BaseModal: typeof import('./src/components/UI/BaseModal.vue')['default']
    BaseSelect: typeof import('./src/components/UI/BaseSelect.vue')['default']
    ContentCard: typeof import('./src/components/Band/ContentCard.vue')['default']
    ContentList: typeof import('./src/components/Band/ContentList.vue')['default']
    IconCheck: typeof import('./src/components/Icons/IconCheck.vue')['default']
    IconMoon: typeof import('./src/components/Icons/IconMoon.vue')['default']
    IconNext: typeof import('./src/components/Icons/IconNext.vue')['default']
    IconNoSound: typeof import('./src/components/Icons/IconNoSound.vue')['default']
    IconPause: typeof import('./src/components/Icons/IconPause.vue')['default']
    IconPlay: typeof import('./src/components/Icons/IconPlay.vue')['default']
    IconPlus: typeof import('./src/components/Icons/IconPlus.vue')['default']
    IconPrevious: typeof import('./src/components/Icons/IconPrevious.vue')['default']
    IconSound: typeof import('./src/components/Icons/IconSound.vue')['default']
    IconSun: typeof import('./src/components/Icons/IconSun.vue')['default']
    InputFile: typeof import('./src/components/form/InputFile.vue')['default']
    MusicPlayer: typeof import('./src/components/MusicPlayer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
  }
}

export {}
